-- Add three new class topics
ALTER TYPE "ClassTopic" ADD VALUE IF NOT EXISTS 'YOUTH';
ALTER TYPE "ClassTopic" ADD VALUE IF NOT EXISTS 'BRAIDING';
ALTER TYPE "ClassTopic" ADD VALUE IF NOT EXISTS 'MAKING_PATTERNS';
